GET http://localhost:3000/admin/dashboard

###

POST http://localhost:8080/admin
Content-Type: application/json

{
    "name": "Kiet",
    "email": "kiet123@gmail.com"
}

###

POST http://localhost:8080/api/user/register
Content-Type: application/json

{
    "name": "Boss",
    "email": "admin",
    "phone": "admin",
    "password": "iamadmin"
}